# Generated by Django 3.2.2 on 2021-10-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_book_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number',
        ),
    ]
